// How to earn each Steam achievement that unlocks an item, from the Isaac wiki "Achievements" table.
// Keyed by Steam achievement ID: [achievement name, unlock condition]. Used by the Items view.
window.ACHIEVEMENTS = {
  "5":["The Harbingers","Defeat Mom"],"6":["A Cube of Meat","Defeat Mom"],"7":["The Book of Revelations","Defeat a Harbinger"],
  "8":["A Noose","Defeat Mom's Heart 3 times"],"9":["The Nail","Complete the Boss Rush as Azazel"],"10":["A Quarter","Defeat Mom's Heart 8 times"],
  "11":["A Fetus in a Jar","Defeat Mom's Heart 9 times"],"12":["A Small Rock","Destroy 100 Tinted Rocks"],"13":["Monstro's Tooth","Beat Chapter 1"],
  "14":["Lil' Chubby","Beat Chapter 2"],"15":["Loki's Horns","Defeat Lokii"],
  "19":["A Bandage","Become Super Bandage Girl by picking up 4 Ball of Bandages in one run"],
  "20":["A Cross","Defeat Isaac as Magdalene"],"21":["A Bag of Pennies","Defeat Isaac as Cain"],"22":["The Book of Sin","Defeat all 7 Deadly Sins"],
  "23":["Little Gish","Defeat Gish"],"24":["Little Steven","Defeat Steven"],"25":["Little C.H.A.D.","Defeat C.H.A.D."],"26":["A Gamekid","Visit 10 Arcades"],
  "27":["A Halo","Defeat Mom, Mom's Heart, or It Lives! using The Bible or XV - The Devil?"],"28":["Mr. Mega","Destroy 10 Tinted Rocks"],
  "29":["The D6","Defeat Isaac as ???"],"30":["The Scissors","Die 100 times"],
  "31":["The Parasite","Pick up 2 'dead' items in one run (Bob's Rotten Head, Dead Cat, Cricket's Head, Tammy's Head)"],
  "35":["Mom's Contact","Obtain three Yes Mother? items in one run"],"36":["The Necronomicon","Use XIII - Death 4 times"],
  "43":["Mom's Knife","Defeat Satan as Isaac"],"44":["The Razor","Defeat Satan as Eve"],"45":["Guardian Angel","Defeat Satan as Magdalene"],
  "46":["A Bag of Bombs","Defeat Satan as Cain"],"47":["Demon Baby","Defeat The Lamb as Azazel"],"48":["Forget Me Now","Defeat Satan as ???"],
  "49":["The D20","Defeat ??? as Isaac"],"50":["Celtic Cross","Defeat ??? as Magdalene"],"51":["Abel","Defeat The Lamb as Cain"],
  "53":["Sacrificial Dagger","Defeat ??? as Eve"],"54":["Bloody Lust","Defeat Isaac as Samson"],"56":["Blood Rights","Defeat Satan as Samson"],
  "57":["The Polaroid","Defeat Isaac 5 times"],"58":["Dad's Key","Pick up both Key Pieces from the Angels in one run"],
  "59":["Blue Candle","Donate 900 coins to the Donation Machine"],"62":["Epic Fetus","Complete The Family Man (challenge #19)"],
  "63":["SMB Super Fan","Complete It's in the Cards (challenge #14)"],"65":["Guppy's Hairball","Become Guppy"],
  "66":["A Forgotten Horseman","Take 10 Angel Room items"],"78":["The Negative","Defeat Satan 5 times"],
  "102":["Robo-Baby 2.0","Complete Computer Savvy (challenge #16)"],"103":["Death's Touch","Complete Waka Waka (challenge #17)"],
  "104":["Technology .5","Complete The Host (challenge #18)"],"105":["Missing No.","Complete the Boss Rush as Lazarus"],
  "106":["Isaac's Tears","Defeat Isaac as Isaac"],"107":["Guillotine","Defeat Isaac as Judas"],"108":["Judas' Shadow","Complete the Boss Rush as Judas"],
  "109":["Maggy's Bow","Complete the Boss Rush as Magdalene"],"110":["Cain's Other Eye","Complete the Boss Rush as Cain"],
  "112":["Eve's Mascara","Complete the Boss Rush as Eve"],"113":["Fate","Defeat ??? as ???"],"114":["???'s Only Friend","Complete the Boss Rush as ???"],
  "115":["Samson's Chains","Complete the Boss Rush as Samson"],"116":["Lazarus' Rags","Defeat Isaac as Lazarus"],"119":["Pandora's Box","Defeat The Lamb as Lazarus"],
  "121":["Blank Card","Defeat Isaac as Eden"],"122":["Book of Secrets","Defeat Satan as Eden"],"124":["Mystery Sack","Defeat The Lamb as Eden"],
  "125":["Undefined","Complete the Boss Rush as Eden"],"126":["Satanic Bible","Defeat Isaac as Azazel"],"128":["Abaddon","Defeat ??? as Azazel"],
  "129":["Isaac's Heart","Defeat Isaac as The Lost"],"130":["The Mind","Defeat Satan as The Lost"],"131":["The Body","Defeat ??? as The Lost"],
  "132":["The Soul","Defeat The Lamb as The Lost"],"133":["The D100","Complete the Boss Rush as The Lost"],
  "134":["Blue Map","Donate 10 coins to the Donation Machine"],"135":["There's Options","Donate 50 coins to the Donation Machine"],
  "136":["Black Candle","Donate 150 coins to the Donation Machine"],"137":["Red Candle","Donate 400 coins to the Donation Machine"],
  "138":["Stop Watch","Donate 999 coins to the Donation Machine"],"139":["Wire Coat Hanger","Defeat Mom's Heart 4 times"],
  "140":["Ipecac","Defeat Mom's Heart 6 times"],"141":["Experimental Treatment","Defeat Mom's Heart 7 times"],"143":["Head of Krampus","Defeat Krampus"],
  "145":["Butter Bean","Destroy 100 poops"],
  "146":["Little Baggy","Pick up 2 syringe items in one run (Roid Rage, The Virus, Growth Hormones, Experimental Treatment, Speed Ball)"],
  "147":["Blood Bag","Use the Blood Donation Machine 30 times"],"148":["The D4","Blow up 30 Slot Machines"],"150":["Rubber Cement","Defeat Mom's Heart 2 times"],
  "155":["Angels","Complete Chapter 6"],"156":["Godhead","Earn all Hard mode completion marks as The Lost"],
  "179":["Fart Baby","Defeat Hush as Isaac"],"180":["Purity","Defeat Hush as Magdalene"],"181":["D12","Defeat Hush as Cain"],"182":["Betrayal","Defeat Hush as Judas"],
  "183":["Fate's Reward","Defeat Hush as ???"],"184":["Athame","Defeat Hush as Eve"],"186":["Maw of the Void","Defeat Hush as Azazel"],
  "187":["Empty Vessel","Defeat Hush as Lazarus"],"188":["Eden's Blessing","Defeat Hush as Eden"],"189":["Sworn Protector","Defeat Hush as The Lost"],
  "190":["Incubus","Defeat Hush as Lilith"],"192":["Lil' Chest","Defeat Ultra Greed as Isaac"],"193":["Censer","Defeat Ultra Greed as Magdalene"],
  "194":["Evil Eye","Defeat Ultra Greed as Cain"],"195":["My Shadow","Defeat Ultra Greed as Judas"],"198":["Lusty Blood","Defeat Ultra Greed as Samson"],
  "200":["Key Bum","Defeat Ultra Greed as Lazarus"],"201":["GB Bug","Defeat Ultra Greed as Eden"],"202":["Zodiac","Defeat Ultra Greed as The Lost"],
  "203":["Box of Friends","Defeat Ultra Greed as Lilith"],"218":["Rune Bag","Defeat Isaac as Lilith"],"219":["Cambion Conception","Defeat ??? as Lilith"],
  "220":["Serpent's Kiss","Defeat Satan as Lilith"],"221":["Succubus","Defeat The Lamb as Lilith"],"222":["Immaculate Conception","Complete the Boss Rush as Lilith"],
  "231":["D8","Complete PRIDE DAY! (challenge #28)"],"232":["Kidney Stone","Complete Onan's Streak (challenge #29)"],
  "233":["Blank Rune","Complete The Guardian (challenge #30)"],"238":["Deep Pockets","Defeat ??? as Keeper"],
  "244":["Wooden Nickel","Donate 33 coins to the Greed Donation Machine"],"276":["Mega","Defeat Mega Satan as every non-tainted character"],
  "282":["D infinity","Defeat Delirium as Isaac"],"283":["Eucharist","Defeat Delirium as Magdalene"],"285":["Shade","Defeat Delirium as Judas"],
  "286":["King Baby","Defeat Delirium as ???"],"288":["Dull Razor","Defeat Delirium as Eve"],"289":["Eden's Soul","Defeat Delirium as Eden"],
  "290":["Dark Prince's Crown","Defeat Delirium as Azazel"],"291":["Compound Fracture","Defeat Delirium as Lazarus"],"292":["Euthanasia","Defeat Delirium as Lilith"],
  "294":["Crooked Penny","Defeat Delirium as Keeper"],"295":["Void","Defeat Delirium as Apollyon"],"296":["D1","Defeat Ultra Greedier as Isaac"],
  "297":["Glyph of Balance","Defeat Ultra Greedier as Magdalene"],"298":["Sack of Sacks","Defeat Ultra Greedier as Cain"],
  "299":["Eye of Belial","Defeat Ultra Greedier as Judas"],"303":["Metronome","Defeat Ultra Greedier as Eden"],"305":["Plan C","Defeat Ultra Greedier as Lazarus"],
  "306":["Duality","Defeat Ultra Greedier as Lilith"],"307":["Dad's Lost Coin","Defeat Ultra Greedier as The Lost"],"308":["Eye of Greed","Defeat Ultra Greedier as Keeper"],
  "315":["Hushy","Defeat Hush as Apollyon"],"316":["Brown Nugget","Defeat Ultra Greed as Apollyon"],
  "318":["Smelter","Defeat Mom's Heart or It Lives! on Hard mode as Apollyon"],"335":["Greed's Gullet","Complete Pong (challenge #35)"],
  "338":["Delirious","Defeat Delirium"],"349":["Black Hole","Defeat 20 Portals"],"350":["Mystery Gift","Destroy 500 rocks"],
  "351":["Sprinkler","Beat Chapter 1 without taking damage"],"352":["Angry Fly","Become Beelzebub"],"353":["Bozo","Destroy 5 rainbow poops"],
  "354":["Broken Modem","Complete 7 Daily Challenges (by touching the trophy at the end)"],"355":["Buddy in a Box","Pick up 5 familiars in one run"],
  "356":["Fast Bombs","Defeat Little Horn 20 times"],"357":["Lil Delirium","Defeat Delirium for the first time"],
  "364":["Coupon","Buy anything from Shops, Devil Rooms or Black Markets 50 times"],"365":["Telekinesis","Beat Chapter 2 without taking damage"],
  "366":["Moving Box","Use Pandora's Box in the Dark Room"],"367":["Jumper Cables","Pick up 2 battery items in one run (9 Volt, The Battery, Car Battery)"],
  "368":["Leprosy","Beat Chapter 3 without taking damage"],"369":["Technology Zero","Pick up 2 technology items in one run"],
  "371":["Mr. ME!","Open 20 Locked Chests"],"372":["7 Seals","Defeat all 5 Harbingers"],"373":["Angelic Prism","Defeat an Angel 10 times"],
  "374":["Pop!","Beat Chapter 4 without taking damage"],"376":["Death's List","Take 25 Deals with the Devil"],"377":["Haemolacria","Pick up Blood Clot 10 times"],
  "378":["Lachryphagy","Collect 10 \"Tears Up\" items or pills in one run"],"379":["Schoolbag","Enter 6 Shops in one run"],
  "380":["Trisagion","Take 25 Angel Room items"],"382":["Flat Stone","Pick up Rubber Cement 5 times"],"383":["Sacrificial Altar","Take 50 Deals with the Devil"],
  "384":["Lil Spewer","Die to your own explosion from an explosive, poisoned tear (Ipecac, Bob's Rotten Head, Fire Mind / Explosivo + Scorpio, or a Horf! pill)"],
  "385":["Blanket","Sleep in 10 beds"],"386":["Marbles","Use 5 Gulp! pills in one run (Placebo uses count)"],
  "387":["Mystery Egg","Have three charmed enemies in the same room"],"392":["Marrow","Defeat Mom's Heart or It Lives! on Hard mode as The Forgotten"],
  "393":["Slipped Rib","Defeat Isaac as The Forgotten"],"394":["Pointy Rib","Defeat Satan as The Forgotten"],"395":["Jaw Bone","Defeat ??? as The Forgotten"],
  "396":["Brittle Bones","Defeat The Lamb as The Forgotten"],"397":["Divorce Papers","Complete the Boss Rush as The Forgotten"],
  "398":["Hallowed Ground","Defeat Hush as The Forgotten"],"400":["Dad's Ring","Defeat Ultra Greedier as The Forgotten"],
  "401":["Book of the Dead","Defeat Delirium as The Forgotten"],"409":["Fruity Plum","Defeat Baby Plum 10 times"],
  "410":["Plum Flute","Let Baby Plum escape instead of defeating her"],"415":["Red Key","Open Mom's Chest in Home"],
  "417":["Book of Virtues","Defeat Isaac as Bethany"],"418":["Urn of Souls","Defeat Satan as Bethany"],"420":["Alabaster Box","Defeat The Lamb as Bethany"],
  "422":["Soul Locket","Defeat Ultra Greed as Bethany"],"423":["Divine Intervention","Defeat Hush as Bethany"],"424":["Vade Retro","Defeat Ultra Greedier as Bethany"],
  "425":["Star of Bethlehem","Defeat Delirium as Bethany"],"429":["The Stairway","Defeat Isaac as Jacob and Esau"],"430":["Red Stew","Defeat Satan as Jacob and Esau"],
  "431":["Birthright","Defeat ??? as Jacob and Esau"],"432":["Damocles","Defeat The Lamb as Jacob and Esau"],"433":["Rock Bottom","Complete the Boss Rush as Jacob and Esau"],
  "434":["Inner Child","Defeat Ultra Greed as Jacob and Esau"],"435":["Vanishing Twin","Defeat Hush as Jacob and Esau"],
  "436":["Genesis","Defeat Ultra Greedier as Jacob and Esau"],"437":["Suplex!","Defeat Delirium as Jacob and Esau"],
  "440":["Meat Cleaver","Defeat Mother as Isaac"],"441":["Options?","Defeat The Beast as Isaac"],"442":["Yuck Heart","Defeat Mother as Magdalene"],
  "443":["Candy Heart","Defeat The Beast as Magdalene"],"444":["Guppy's Eye","Defeat Mother as Cain"],"445":["A Pound of Flesh","Defeat The Beast as Cain"],
  "446":["Akeldama","Defeat Mother as Judas"],"447":["Redemption","Defeat The Beast as Judas"],"448":["Eternal D6","Defeat Mother as ???"],
  "449":["Montezuma's Revenge","Defeat The Beast as ???"],"450":["Bird Cage","Defeat Mother as Eve"],"451":["Cracked Orb","Defeat The Beast as Eve"],
  "452":["Bloody Gust","Defeat Mother as Samson"],"453":["Empty Heart","Defeat The Beast as Samson"],"455":["Lil Abaddon","Defeat The Beast as Azazel"],
  "456":["Tinytoma","Defeat Mother as Lazarus"],"457":["Astral Projection","Defeat The Beast as Lazarus"],"459":["Everything Jar","Defeat The Beast as Eden"],
  "460":["Lost Soul","Defeat Mother as The Lost"],"461":["Hungry Soul","Defeat The Beast as The Lost"],"462":["Blood Puppy","Defeat Mother as Lilith"],
  "463":["C Section","Defeat The Beast as Lilith"],"464":["Keeper's Sack","Defeat Mother as Keeper"],"465":["Keeper's Box","Defeat The Beast as Keeper"],
  "466":["Lil Portal","Defeat Mother as Apollyon"],"467":["Worm Friend","Defeat The Beast as Apollyon"],"468":["Bone Spurs","Defeat Mother as The Forgotten"],
  "469":["Spirit Shackles","Defeat The Beast as The Forgotten"],"470":["Revelation","Defeat Mother as Bethany"],"471":["Jar of Wisps","Defeat The Beast as Bethany"],
  "472":["Magic Skin","Defeat Mother as Jacob and Esau"],"473":["Friend Finder","Defeat The Beast as Jacob and Esau"],
  "491":["Glitched Crown","Defeat The Beast as Tainted Isaac"],"492":["Belly Jelly","Defeat The Beast as Tainted Magdalene"],
  "494":["Sanguine Bond","Defeat The Beast as Tainted Judas"],"495":["The Swarm","Defeat The Beast as Tainted ???"],"496":["Heartbreak","Defeat The Beast as Tainted Eve"],
  "497":["Larynx","Defeat The Beast as Tainted Samson"],"498":["Azazel's Rage","Defeat The Beast as Tainted Azazel"],"499":["Salvation","Defeat The Beast as Tainted Lazarus"],
  "500":["TMTRAINER","Defeat The Beast as Tainted Eden"],"501":["Sacred Orb","Defeat The Beast as Tainted Lost"],"502":["Twisted Pair","Defeat The Beast as Tainted Lilith"],
  "503":["Strawman","Defeat The Beast as Tainted Keeper"],"504":["Echo Chamber","Defeat The Beast as Tainted Apollyon"],
  "505":["Isaac's Tomb","Defeat The Beast as Tainted Forgotten"],"506":["Vengeful Spirit","Defeat The Beast as Tainted Bethany"],
  "507":["Esau Jr.","Defeat The Beast as Tainted Jacob"],"517":["Dirty Mind","Complete Scat Man (challenge #36)"],
  "519":["Purgatory","Complete Baptism by Fire (challenge #38)"],"520":["Spirit Sword","Complete Isaac's Awakening (challenge #39)"],
  "546":["Brimstone Bombs","After breaking Hornfel's minecart, kill him before he escapes"],
  "547":["Mega Mush","Earn all Hard mode completion marks for all non-tainted characters"],"582":["Member Card","Spend 40+ coins in a single Shop"],
  "583":["Golden Razor","In one run, have 99 coins, then spend all of them"],"584":["Spindown Dice","Defeat Delirium as Tainted Isaac"],
  "585":["Hypercoagulation","Defeat Delirium as Tainted Magdalene"],"586":["Bag of Crafting","Defeat Delirium as Tainted Cain"],
  "587":["Dark Arts","Defeat Delirium as Tainted Judas"],"588":["IBS","Defeat Delirium as Tainted ???"],"589":["Sumptorium","Defeat Delirium as Tainted Eve"],
  "590":["Berserk!","Defeat Delirium as Tainted Samson"],"591":["Hemoptysis","Defeat Delirium as Tainted Azazel"],"592":["Flip","Defeat Delirium as Tainted Lazarus"],
  "594":["Ghost Bombs","Defeat Delirium as Tainted Lost"],"595":["Gello","Defeat Delirium as Tainted Lilith"],"596":["Keeper's Kin","Defeat Delirium as Tainted Keeper"],
  "597":["Abyss","Defeat Delirium as Tainted Apollyon"],"598":["Decap Attack","Defeat Delirium as Tainted Forgotten"],
  "599":["Lemegeton","Defeat Delirium as Tainted Bethany"],"600":["Anima Sola","Defeat Delirium as Tainted Jacob"],
  "636":["Death Certificate","Earn all Hard mode completion marks for all characters, including tainted ones"]
};
