// Challenges from the Isaac wiki, matched to Steam achievement IDs.
// req: AND of OR-groups of achievement IDs that unlock the challenge ([] = available from the start).
// done: achievement granted for beating the challenge.
window.CHALLENGES = [
  {"n":1,"name":"Pitch Black","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"89","reward":"Rune of Hagalaz"},
  {"n":2,"name":"High Brow","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"90","reward":"Rune of Jera"},
  {"n":3,"name":"Head Trauma","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"91","reward":"Rune of Ehwaz"},
  {"n":4,"name":"Darkness Falls","char":"Eve","goal":"Satan","req":[["157"]],"reqText":"Defeat Mom's Heart 11 times and unlock Eve","done":"92","reward":"Rune of Dagaz"},
  {"n":5,"name":"The Tank","char":"Magdalene","goal":"Mom","req":[["158"]],"reqText":"Have 7 or more Red Heart Containers at one time","done":"93","reward":"Rune of Ansuz"},
  {"n":6,"name":"Solar System","char":"Isaac","goal":"Mom's Heart","req":[["159"]],"reqText":"Defeat Mom's Heart 3 times","done":"94","reward":"Rune of Perthro"},
  {"n":7,"name":"Suicide King","char":"Lazarus","goal":"Isaac","req":[["160"]],"reqText":"Defeat Mom's Heart 11 times and unlock Lazarus","done":"120","reward":"Suicide King"},
  {"n":8,"name":"Cat Got Your Tongue","char":"Isaac","goal":"Mom","req":[["161"]],"reqText":"Become Guppy","done":"96","reward":"Rune of Algiz"},
  {"n":9,"name":"Demo Man","char":"Isaac","goal":"Mom's Heart","req":[["162"]],"reqText":"Defeat Mom's Heart 9 times","done":"97","reward":"Chaos Card"},
  {"n":10,"name":"Cursed!","char":"Magdalene","goal":"Mom","req":[["163"]],"reqText":"Have 7 or more Red Heart Containers at one time","done":"98","reward":"Credit Card"},
  {"n":11,"name":"Glass Cannon","char":"Judas","goal":"Satan","req":[["164"]],"reqText":"Beat The Family Man (challenge #19), defeat Lokii, and unlock Judas and It Lives!","done":"99","reward":"Rules Card"},
  {"n":12,"name":"When Life Gives You Lemons","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"100","reward":"Card Against Humanity"},
  {"n":13,"name":"Beans!","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"60","reward":"Burnt Penny"},
  {"n":14,"name":"It's in the Cards","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"63","reward":"SMB Super Fan"},
  {"n":15,"name":"Slow Roll","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"101","reward":"Swallowed Penny"},
  {"n":16,"name":"Computer Savvy","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"102","reward":"Robo-Baby 2.0"},
  {"n":17,"name":"Waka Waka","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"103","reward":"Death's Touch"},
  {"n":18,"name":"The Host","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"104","reward":"Technology .5"},
  {"n":19,"name":"The Family Man","char":"Isaac","goal":"Isaac","req":[["165"]],"reqText":"Pick up both Key Pieces from the Angels in one run","done":"62","reward":"Epic Fetus"},
  {"n":20,"name":"Purist","char":"Isaac","goal":"Mom's Heart","req":[["166"]],"reqText":"Defeat Mom","done":"95","reward":"Rune of Berkano"},
  {"n":21,"name":"XXXXXXXXL","char":"Isaac","goal":"Mom's Heart","req":[["265"]],"reqText":"Defeat Mom","done":"224","reward":"Gold Heart"},
  {"n":22,"name":"SPEED!","char":"Isaac","goal":"Mom's Heart","req":[["266"]],"reqText":"Defeat Mom","done":"225","reward":"Get out of Jail Free Card"},
  {"n":23,"name":"Blue Bomber","char":"???","goal":"Satan","req":[["267"]],"reqText":"Destroy 10 Tinted Rocks and defeat Mom's Heart 11 times","done":"226","reward":"Gold Bomb"},
  {"n":24,"name":"PAY TO PLAY","char":"Isaac","goal":"Isaac","req":[["268"]],"reqText":"Defeat Isaac as Cain and destroy 10 Tinted Rocks","done":"227","reward":"2 new pills"},
  {"n":25,"name":"Have a Heart","char":"Isaac","goal":"Mom's Heart","req":[["269"]],"reqText":"Defeat Mom","done":"228","reward":"2 new pills"},
  {"n":26,"name":"I RULE!","char":"Isaac","goal":"Mega Satan","req":[["270"]],"reqText":"Defeat Mega Satan and unlock The Negative","done":"229","reward":"Poker Chip"},
  {"n":27,"name":"BRAINS!","char":"???","goal":"???","req":[["271"]],"reqText":"Defeat Isaac 5 times","done":"230","reward":"Stud Finder"},
  {"n":28,"name":"PRIDE DAY!","char":"Isaac","goal":"Mom's Heart","req":[["272"]],"reqText":"Defeat Mom","done":"231","reward":"D8"},
  {"n":29,"name":"Onan's Streak","char":"Judas","goal":"Isaac","req":[["273"]],"reqText":"Unlock Judas and It Lives!","done":"232","reward":"Kidney Stone"},
  {"n":30,"name":"The Guardian","char":"Isaac","goal":"Mom's Heart","req":[["274"]],"reqText":"Defeat Mom","done":"233","reward":"Blank Rune"},
  {"n":31,"name":"Backasswards","char":"Isaac","goal":"Burning Basement","req":[["78"],["205","206","207","208","209","210","211","212","213","214","215","216","217","317","403","427","439","601","602","603","604","605","606","607","608","609","610","611","612","613","614","615","616","617"]],"reqText":"Defeat Mega Satan and unlock The Negative","done":"331","reward":"Laz Bleeds More!"},
  {"n":32,"name":"Aprils Fool","char":"Isaac","goal":"Mom's Heart","req":[["4"]],"reqText":"Defeat Mom","done":"332","reward":"Maggy Now Holds a Pill!"},
  {"n":33,"name":"Pokey Mans","char":"Isaac","goal":"Isaac","req":[["34"]],"reqText":"Defeat Mom's Heart 11 times","done":"333","reward":"Charged Key"},
  {"n":34,"name":"Ultra Hard","char":"Isaac","goal":"Mega Satan","req":[["78"],["205","206","207","208","209","210","211","212","213","214","215","216","217","317","403","427","439","601","602","603","604","605","606","607","608","609","610","611","612","613","614","615","616","617"]],"reqText":"Defeat Mega Satan and unlock The Negative","done":"334","reward":"Samson Feels Healthy!"},
  {"n":35,"name":"Pong","char":"Isaac","goal":"???","req":[["271"]],"reqText":"Defeat Isaac 5 times","done":"335","reward":"Greed's Gullet"},
  {"n":36,"name":"Scat Man","char":"Isaac","goal":"Mom","req":[],"reqText":"","done":"517","reward":"Dirty Mind"},
  {"n":37,"name":"Bloody Mary","char":"Bethany","goal":"Satan","req":[["404"],["147"],["34"]],"reqText":"Unlock Bethany, Blood Bag, and It Lives!","done":"518","reward":"Sigil of Baphomet"},
  {"n":38,"name":"Baptism by Fire","char":"Bethany","goal":"Isaac","req":[["418"],["34"],["71"]],"reqText":"Defeat Satan as Bethany, defeat Mom's Heart 11 times, and unlock Maggy's Faith","done":"519","reward":"Purgatory"},
  {"n":39,"name":"Isaac's Awakening","char":"Isaac","goal":"Mother","req":[["440","442","444","446","448","450","452","454","456","458","460","462","464","466","468","470","472","549","551","553","555","557","559","561","563","565","567","569","571","573","575","577","579","581"]],"reqText":"Defeat Mother","done":"520","reward":"Spirit Sword"},
  {"n":40,"name":"Seeing Double","char":"Jacob & Esau","goal":"Mom's Heart","req":[["440","442","444","446","448","450","452","454","456","458","460","462","464","466","468","470","472","549","551","553","555","557","559","561","563","565","567","569","571","573","575","577","579","581"]],"reqText":"Defeat Mother","done":"521","reward":"Broken Glasses"},
  {"n":41,"name":"Pica Run","char":"Isaac","goal":"Isaac","req":[["34"],["386"]],"reqText":"Defeat Mom's Heart 11 times and unlock Marbles","done":"522","reward":"Ice Cube"},
  {"n":42,"name":"Hot Potato","char":"Tainted Forgotten","goal":"Satan","req":[["488"]],"reqText":"Unlock Tainted Forgotten","done":"531","reward":"The Chariot"},
  {"n":43,"name":"Cantripped!","char":"Tainted Cain","goal":"Mom","req":[["476"]],"reqText":"Unlock Tainted Cain","done":"532","reward":"Justice"},
  {"n":44,"name":"Red Redemption","char":"Tainted Jacob","goal":"Mother","req":[["490"]],"reqText":"Unlock Tainted Jacob","done":"533","reward":"The Hermit"},
  {"n":45,"name":"DELETE THIS","char":"Isaac","goal":"???","req":[["483"]],"reqText":"Unlock Tainted Eden","done":"538","reward":"Temperance"}
];
