# Rebuilds js/marks-art.js and img/portraits.png from an installed copy of the game.
#
#   powershell -ExecutionPolicy Bypass -File tools\extract-sprites.ps1
#
# Crops come from the game's own .anm2 files: completion_widget.anm2 for the marks,
# characterportraits.anm2 for the portraits.
#
# The marks come out as pixel data, not as an image: 16x16 palette indices per tile, which
# js/art.js turns into SVG rectangles. A rectangle is sharp at every size and at every zoom
# level, which a scaled PNG is not - and it cannot fail to load.
# The portraits stay a PNG sheet (48x48 tiles, too many colours to be worth vectorising) and
# are drawn as a plain CSS background sprite.
Add-Type -AssemblyName System.Drawing
$game = "X:\SteamLibrary\steamapps\common\The Binding of Isaac Rebirth\resources\gfx\ui"
$root = Split-Path $PSScriptRoot -Parent
$out  = Join-Path $root "img"
New-Item -ItemType Directory -Force -Path $out | Out-Null

# ---------- marks ----------
# Source x of each 16x16 tile, in window.MARKS order (js/art.js).
$markX = @(64, 32, 48, 0, 16, 112, 80, 128, 192, 160, 176, 144)
# Rows: the note is tinted per difficulty and per mode.
$rows = [ordered]@{ normal = 112; hard = 96; greed = 320; greedier = 336 }

# Palette index -> one character. '.' is reserved for transparent.
$DIGITS = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"

$src = [System.Drawing.Bitmap]::FromFile("$game\completion_widget.png")
$lines = @()
$lines += "// Generated by tools/extract-sprites.ps1 from the game's completion_widget.png - do not edit by hand."
$lines += "// Per variant: a palette and one 256-character tile per mark, in window.MARKS order. Each character"
$lines += "// is a palette index (0-9, a-z, A-Z), or a dot for a transparent pixel; tiles are 16x16, row by row."
$lines += "window.MARK_ART = {"
$lines += "  size: 16,"
$lines += "  variants: {"

foreach ($vname in $rows.Keys) {
  $y0 = $rows[$vname]
  # Collect the palette for this row first: colour -> index.
  $pal = [ordered]@{}
  foreach ($x0 in $markX) {
    for ($y = $y0; $y -lt $y0 + 16; $y++) {
      for ($x = $x0; $x -lt $x0 + 16; $x++) {
        $p = $src.GetPixel($x, $y)
        if ($p.A -eq 0) { continue }
        $k = "#{0:x2}{1:x2}{2:x2}{3:x2}" -f $p.R, $p.G, $p.B, $p.A
        if (-not $pal.Contains($k)) { $pal[$k] = $pal.Count }
      }
    }
  }
  if ($pal.Count -gt $DIGITS.Length) { throw "$vname needs $($pal.Count) palette entries, only $($DIGITS.Length) digits available" }

  $tiles = @()
  foreach ($x0 in $markX) {
    $sb = New-Object System.Text.StringBuilder
    for ($y = $y0; $y -lt $y0 + 16; $y++) {
      for ($x = $x0; $x -lt $x0 + 16; $x++) {
        $p = $src.GetPixel($x, $y)
        if ($p.A -eq 0) { [void]$sb.Append('.'); continue }
        $k = "#{0:x2}{1:x2}{2:x2}{3:x2}" -f $p.R, $p.G, $p.B, $p.A
        [void]$sb.Append($DIGITS[$pal[$k]])
      }
    }
    $tiles += "      '$($sb.ToString())'"
  }
  $palJs = (($pal.Keys | ForEach-Object { "'$_'" }) -join ', ')
  $lines += "    $vname`: {"
  $lines += "      pal: [$palJs],"
  $lines += "      tiles: ["
  $lines += ($tiles -join ",`r`n")
  $lines += "      ],"
  $lines += "    },"
}
$lines += "  },"

# The interior of a glyph - the part that takes the player colours - is whatever is solid on
# the plain note, where the game draws the body and nothing else. On the hard, Greed and
# Greedier notes the same body is wrapped in a coloured ring, and on several glyphs that ring
# covers more pixels than the body does, so it cannot be found by counting colours.
$lines += "  // Solid body of each mark, taken from the plain note: '1' where the player colour goes."
$lines += "  bodies: ["
$bodies = @()
foreach ($x0 in $markX) {
  $sb = New-Object System.Text.StringBuilder
  for ($y = $rows['normal']; $y -lt $rows['normal'] + 16; $y++) {
    for ($x = $x0; $x -lt $x0 + 16; $x++) {
      [void]$sb.Append($(if ($src.GetPixel($x, $y).A -eq 255) { '1' } else { '.' }))
    }
  }
  $bodies += "    '$($sb.ToString())'"
}
$lines += ($bodies -join ",`r`n")
$lines += "  ],"
$lines += "};"
$src.Dispose()
Set-Content -Path (Join-Path $root "js\marks-art.js") -Value ($lines -join "`r`n") -Encoding UTF8
"js/marks-art.js  $($markX.Count) marks x $($rows.Count) variants"

# ---------- portraits ----------
# key -> crop on CharacterMenu.png / CharacterMenuAlt.png (frame 0 of characterportraits.anm2).
$port = [ordered]@{
  isaac     = @(176, 288); magdalene = @(176, 336); cain      = @(272, 288); judas    = @(272, 336)
  bluebaby  = @(368, 288); eve       = @(368, 336); samson    = @(176, 384); azazel   = @(272, 384)
  lazarus   = @(368, 384); eden      = @(176, 432); lost      = @(416, 288); lilith   = @(320, 432)
  keeper    = @(368, 432); apollyon  = @(384, 928); forgotten = @(336, 928); bethany  = @(464, 336)
  jacob     = @(464, 432)
}
# Tiles stay at their native 48x48: the browser upscales them with image-rendering: pixelated,
# which is sharper than baking in a scale that then gets resampled again.
$P = 48
$sheets = @([System.Drawing.Bitmap]::FromFile("$game\main menu\charactermenu.png"),
            [System.Drawing.Bitmap]::FromFile("$game\main menu\charactermenualt.png"))
$bm = New-Object System.Drawing.Bitmap(($port.Count * $P), (2 * $P), [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
$g = [System.Drawing.Graphics]::FromImage($bm)
$g.CompositingMode = 'SourceCopy'
for ($row = 0; $row -lt 2; $row++) {
  $col = 0
  foreach ($k in $port.Keys) {
    $c = $port[$k]
    $rect = New-Object System.Drawing.Rectangle($c[0], $c[1], 48, 48)
    $tile = $sheets[$row].Clone($rect, [System.Drawing.Imaging.PixelFormat]::Format32bppArgb)
    $g.DrawImage($tile, (New-Object System.Drawing.Rectangle(($col * $P), ($row * $P), $P, $P)))
    $tile.Dispose(); $col++
  }
}
$g.Dispose()
$ms = New-Object System.IO.MemoryStream
$bm.Save($ms, [System.Drawing.Imaging.ImageFormat]::Png)
$b64 = [System.Convert]::ToBase64String($ms.ToArray())
$ms.Dispose(); $bm.Dispose()
$sheets | ForEach-Object { $_.Dispose() }

# The sheet ships inside the JS as a data URI rather than as a file in img/: the page then has
# no second request that can 404, be cached half-written, or go missing when the site is copied.
$keysJs = (($port.Keys | ForEach-Object { "'$_'" }) -join ', ')
$pl = @()
$pl += "// Generated by tools/extract-sprites.ps1 from the game's CharacterMenu.png and CharacterMenuAlt.png."
$pl += "// A $($port.Count)x2 sheet of $P`x$P tiles: row 0 is the normal character, row 1 the tainted one."
$pl += "window.PORTRAIT_ART = {"
$pl += "  tile: $P, cols: $($port.Count), rows: 2,"
$pl += "  keys: [$keysJs],"
$pl += "  src: 'data:image/png;base64,$b64',"
$pl += "};"
Set-Content -Path (Join-Path $root "js\portraits-art.js") -Value ($pl -join "`r`n") -Encoding UTF8
if (Test-Path $out) { Remove-Item $out -Recurse -Force }
"js/portraits-art.js  $($port.Count * $P)x$(2 * $P)  order: $(($port.Keys) -join ',')"


